version: '2.4'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.${SUBNET}.0/24
services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    links:
      - app
    environment:
      - VIRTUAL_HOST
    networks:
      - back
      - lb_web
  db:
    image: postgres:${POSTGRES_VERSION:10.6}
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: .env
    networks:
      - back
  redis:
    image: redis:${REDIS_VERSION:-1.2.1}
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - back
  app:
    image: chocobozzz/peertube:${PEERTUBE_VERSION:-production-stretch}
    restart: always
    links:
      - db
    depends_on:
      - db
      - redis
    env_file: .env
    volumes:
      - ./data/peertube:/data
    networks:
      - back
