#!/bin/bash -eux

POSTGRES_PASSWORD=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | xargs`

mkdir -p /data/dump

echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" > .env
echo "POSTGRES_USER=peertube" >> .env

echo "PEERTUBE_WEBSERVER_HOSTNAME=" >> .env
echo "PEERTUBE_WEBSERVER_PORT=443" >> .env
echo "PEERTUBE_WEBSERVER_HTTPS=true" >> .env
echo "PEERTUBE_ADMIN_EMAIL=" >> .env
echo "PEERTUBE_DB_HOSTNAME=db" >> .env
echo "PEERTUBE_DB_USERNAME=peertube" >> .env
echo "PEERTUBE_DB_PASSWORD=peertube" >> .env
echo "PEERTUBE_SIGNUP_ENABLED=true" >> .env
echo "PEERTUBE_TRANSCODING_ENABLED=true" >> .env
echo "PEERTUBE_REDIS_HOSTNAME=redis" >> .env
echo "PEERTUBE_SMTP_HOSTNAME=${MAIL_HOST}" >> .env
echo "PEERTUBE_SMTP_PORT=${MAIL_PORT}" >> .env
echo "PEERTUBE_SMTP_FROM=${MAIL_USER}" >> .env
echo "PEERTUBE_SMTP_USERNAME=${MAIL_USER}" >> .env
echo "PEERTUBE_SMTP_PASSWORD=${MAIL_PASS}" >> .env
echo "PEERTUBE_SMTP_TLS=false" >> .env
echo "PEERTUBE_DISABLE_TLS=false" >> .env
